# Generated by Django 4.2 on 2024-07-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
    ]
